[package]
name = "cycles_numerologie_du_tarot"
version = "0.1.0"
edition = "2024"

[dependencies]

[[example]]
name = "cycle"
path = "exemples/cycle.rs"

[lib]
name = "cycles_numerologie_du_tarot"
crate-type = ["rlib", "staticlib"]